// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: service.proto

package sumallpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NumberAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *NumberAddRequest) Reset() {
	*x = NumberAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberAddRequest) ProtoMessage() {}

func (x *NumberAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberAddRequest.ProtoReflect.Descriptor instead.
func (*NumberAddRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *NumberAddRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x73, 0x75, 0x6d, 0x61, 0x6c, 0x6c, 0x22, 0x24, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x25, 0x0a,
	0x0b, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x4c, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x53, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x12,
	0x18, 0x2e, 0x73, 0x75, 0x6d, 0x61, 0x6c, 0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x75, 0x6d, 0x61,
	0x6c, 0x6c, 0x2e, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x73, 0x75, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []interface{}{
	(*NumberAddRequest)(nil), // 0: sumall.NumberAddRequest
	(*SumResponse)(nil),      // 1: sumall.SumResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: sumall.SumAllService.SumAll:input_type -> sumall.NumberAddRequest
	1, // 1: sumall.SumAllService.SumAll:output_type -> sumall.SumResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumAllServiceClient is the client API for SumAllService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumAllServiceClient interface {
	SumAll(ctx context.Context, opts ...grpc.CallOption) (SumAllService_SumAllClient, error)
}

type sumAllServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumAllServiceClient(cc grpc.ClientConnInterface) SumAllServiceClient {
	return &sumAllServiceClient{cc}
}

func (c *sumAllServiceClient) SumAll(ctx context.Context, opts ...grpc.CallOption) (SumAllService_SumAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SumAllService_serviceDesc.Streams[0], "/sumall.SumAllService/SumAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumAllServiceSumAllClient{stream}
	return x, nil
}

type SumAllService_SumAllClient interface {
	Send(*NumberAddRequest) error
	CloseAndRecv() (*SumResponse, error)
	grpc.ClientStream
}

type sumAllServiceSumAllClient struct {
	grpc.ClientStream
}

func (x *sumAllServiceSumAllClient) Send(m *NumberAddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sumAllServiceSumAllClient) CloseAndRecv() (*SumResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SumAllServiceServer is the server API for SumAllService service.
type SumAllServiceServer interface {
	SumAll(SumAllService_SumAllServer) error
}

// UnimplementedSumAllServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumAllServiceServer struct {
}

func (*UnimplementedSumAllServiceServer) SumAll(SumAllService_SumAllServer) error {
	return status.Errorf(codes.Unimplemented, "method SumAll not implemented")
}

func RegisterSumAllServiceServer(s *grpc.Server, srv SumAllServiceServer) {
	s.RegisterService(&_SumAllService_serviceDesc, srv)
}

func _SumAllService_SumAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SumAllServiceServer).SumAll(&sumAllServiceSumAllServer{stream})
}

type SumAllService_SumAllServer interface {
	SendAndClose(*SumResponse) error
	Recv() (*NumberAddRequest, error)
	grpc.ServerStream
}

type sumAllServiceSumAllServer struct {
	grpc.ServerStream
}

func (x *sumAllServiceSumAllServer) SendAndClose(m *SumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sumAllServiceSumAllServer) Recv() (*NumberAddRequest, error) {
	m := new(NumberAddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SumAllService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sumall.SumAllService",
	HandlerType: (*SumAllServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumAll",
			Handler:       _SumAllService_SumAll_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
